# 1) Creation a DataFrame

#### 1) Creating data frame using list

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
routine_data= [
    [7,5,3],
    [6,3,6],
    [8,6,2],
    [5,2,7]
]

print(routine_data)

[[7, 5, 3], [6, 3, 6], [8, 6, 2], [5, 2, 7]]

In [4]:
df = pd.DataFrame(routine_data,columns=['sleep_hrs','study_hrs','phone-hrs'])
print(df)

   sleep_hrs  study_hrs  phone-hrs
0          7          5          3
1          6          3          6
2          8          6          2
3          5          2          7

In [5]:
df

   sleep_hrs  study_hrs  phone-hrs
0          7          5          3
1          6          3          6
2          8          6          2
3          5          2          7

In [6]:
routine_dict = {
    'name':['aarav','diya','kabri','mera','rohan','sana'],
    'sleep_hrs':[7,6,8,5,0,0],
    'study_hrs':[5,3,6,2,0,0],
    'phone_hrs':[3,6,2,7,0,0]
}
print(routine_dict)

{'name': ['aarav', 'diya', 'kabri', 'mera', 'rohan', 'sana'], 'sleep_hrs': [7, 6, 8, 5, 0, 0], 'study_hrs': [5, 3, 6, 2, 0, 0], 'phone_hrs': [3, 6, 2, 7, 0, 0]}

In [7]:
routine = pd.DataFrame(routine_dict)
routine

    name  sleep_hrs  study_hrs  phone_hrs
0  aarav          7          5          3
1   diya          6          3          6
2  kabri          8          6          2
3   mera          5          2          7
4  rohan          0          0          0
5   sana          0          0          0

# 3) Creating DataFrame using read_csv(food orders)

In [8]:
food = pd.read_csv('food_orders.csv')
print(type(food))
food

<class 'pandas.DataFrame'>

,order_id,order_date,day,order_hour,meal_time,city,area,customer,restaurant,cuisines,...,quantity,order_value,coupon_code,discount,payment_mode,delivery_mins,customer_rating,review,restaurant_rating,restaurant_votes
0,FD50000,30-06-2024,Sunday,22,Dinner,Mumbai,Thane,Rahul S.,The Healthy Bowl,Healthy Food|Salads,...,3,730,BIRYANI30,150,UPI,35,4.0,Worth every rupee.,3.8,2100
1,FD49999,30-06-2024,Sunday,22,Dinner,Mumbai,Andheri,Riya K.,Biryani Junction,Biryani|Hyderabadi|Mughlai,...,5,1140,NaN,0,Card,36,5.0,NaN,4.4,18400
2,FD49998,30-06-2024,Sunday,20,Dinner,Delhi,Karol Bagh,Pranav A.,Paratha Paradise,North Indian|Breakfast,...,3,280,NaN,0,Card,49,4.0,Portion size was great.,4.4,6100
3,FD49997,30-06-2024,Sunday,20,Dinner,Mumbai,Powai,Meera K.,Biryani Junction,Biryani|Hyderabadi|Mughlai,...,6,1660,NaN,0,Cash,34,4.0,Delivered super fast.,4.4,18400
4,FD49996,30-06-2024,Sunday,19,Dinner,Delhi,Connaught Place,Meera S.,Paratha Paradise,North Indian|Breakfast,...,2,160,WELCOME50,80,Cash,25,3.0,NaN,4.4,6100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1498,FD48505,01-01-2024,Monday,23,Late Night,Hyderabad,Gachibowli,Gauri K.,Biryani Junction,Biryani|Hyderabadi|Mughlai,...,3,730,NaN,0,UPI,47,4.0,"Hot and tasty, loved it!",4.4,18400
1499,FD48504,01-01-2024,Monday,23,Late Night,Mumbai,Thane,Priya S.,Pizza Plaza,Pizza|Italian|Fast Food,...,2,378,NaN,0,UPI,43,4.0,NaN,4.0,16800
1500,FD48503,01-01-2024,Monday,19,Dinner,Bengaluru,HSR Layout,Aarav S.,Wok & Roll,Chinese|Thai,...,3,560,BIRYANI30,150,Card,43,5.0,NaN,4.0,6400
1501,FD48502,01-01-2024,Monday,13,Lunch,Bengaluru,Indiranagar,Karan K.,Biryani Junction,Biryani|Hyderabadi|Mughlai,...,2,560,NaN,0,Card,45,NaN,NaN,4.4,18400
1502,FD48501,01-01-2024,Monday,8,Breakfast,Pune,Baner,Isha S.,Chai & Snacks,Beverages|Snacks,...,2,50,NaN,0,Cash,21,5.0,"Hot and tasty, loved it!",4.1,3900

In [9]:
food.head()

,order_id,order_date,day,order_hour,meal_time,city,area,customer,restaurant,cuisines,...,quantity,order_value,coupon_code,discount,payment_mode,delivery_mins,customer_rating,review,restaurant_rating,restaurant_votes
0,FD50000,30-06-2024,Sunday,22,Dinner,Mumbai,Thane,Rahul S.,The Healthy Bowl,Healthy Food|Salads,...,3,730,BIRYANI30,150,UPI,35,4.0,Worth every rupee.,3.8,2100
1,FD49999,30-06-2024,Sunday,22,Dinner,Mumbai,Andheri,Riya K.,Biryani Junction,Biryani|Hyderabadi|Mughlai,...,5,1140,NaN,0,Card,36,5.0,NaN,4.4,18400
2,FD49998,30-06-2024,Sunday,20,Dinner,Delhi,Karol Bagh,Pranav A.,Paratha Paradise,North Indian|Breakfast,...,3,280,NaN,0,Card,49,4.0,Portion size was great.,4.4,6100
3,FD49997,30-06-2024,Sunday,20,Dinner,Mumbai,Powai,Meera K.,Biryani Junction,Biryani|Hyderabadi|Mughlai,...,6,1660,NaN,0,Cash,34,4.0,Delivered super fast.,4.4,18400
4,FD49996,30-06-2024,Sunday,19,Dinner,Delhi,Connaught Place,Meera S.,Paratha Paradise,North Indian|Breakfast,...,2,160,WELCOME50,80,Cash,25,3.0,NaN,4.4,6100

# 4) Creating DataFrame using read_csv (daily rides)

In [10]:
rides = pd.read_csv('daily_rides.csv')
print(type(rides))
rides.head()

<class 'pandas.DataFrame'>

,ride_id,date,hour,city,pickup_area,drop_area,ride_type,rider,driver,distance_km,duration_mins,weather,surge,fare,payment_mode,status,cancelled_by,driver_rating,tip
0,RD25000,30-06-2024,18,Mumbai,Bandra,CST,Mini,Nikhil S.,Vijay Naik,20.7,117,Rainy,N,360.0,UPI,Completed,NaN,4.0,10
1,RD24999,30-06-2024,15,Mumbai,Mumbai Airport,Bandra,Mini,Aarav K.,Vijay Naik,30.6,150,Rainy,N,509.0,Wallet,Completed,NaN,4.0,50
2,RD24998,30-06-2024,12,Pune,Hadapsar,Hinjewadi,Bike,Riya S.,Rajesh Kumar,12.6,45,Rainy,Y,167.0,UPI,Completed,NaN,5.0,0
3,RD24997,30-06-2024,9,Hyderabad,HITEC City,Gachibowli,Sedan,Rohan A.,Venkat Raju,1.2,8,Rainy,Y,144.0,Card,Completed,NaN,NaN,10
4,RD24996,30-06-2024,9,Mumbai,Dadar,Mumbai Airport,Auto,Nikhil K.,Vijay Naik,20.7,102,Sunny,N,278.0,Card,Completed,NaN,4.0,20

# DataFrame Attributes and methods:

## 5) Shape

In [11]:
food.shape

(1503, 22)

In [12]:
rides.shape

(1000, 19)

In [13]:
routine.shape

(6, 4)

## 6) dtypes

In [14]:
rides.dtypes

ride_id              str
date                 str
hour               int64
city                 str
pickup_area          str
drop_area            str
ride_type            str
rider                str
driver               str
distance_km      float64
duration_mins      int64
weather              str
surge                str
fare             float64
payment_mode         str
status               str
cancelled_by         str
driver_rating    float64
tip                int64
dtype: object

##  7) index

In [15]:
food.index

RangeIndex(start=0, stop=1503, step=1)

In [16]:
rides.index

RangeIndex(start=0, stop=1000, step=1)

In [17]:
routine.index

RangeIndex(start=0, stop=6, step=1)

In [18]:
routine

    name  sleep_hrs  study_hrs  phone_hrs
0  aarav          7          5          3
1   diya          6          3          6
2  kabri          8          6          2
3   mera          5          2          7
4  rohan          0          0          0
5   sana          0          0          0

# 8) columns

In [19]:
food.columns

Index(['order_id', 'order_date', 'day', 'order_hour', 'meal_time', 'city',
       'area', 'customer', 'restaurant', 'cuisines', 'dishes', 'veg_nonveg',
       'quantity', 'order_value', 'coupon_code', 'discount', 'payment_mode',
       'delivery_mins', 'customer_rating', 'review', 'restaurant_rating',
       'restaurant_votes'],
      dtype='str')

In [20]:
routine.columns

Index(['name', 'sleep_hrs', 'study_hrs', 'phone_hrs'], dtype='str')

# 9) Values

In [21]:
routine_values = routine.values

In [22]:
print(routine_values)

[['aarav' 7 5 3]
 ['diya' 6 3 6]
 ['kabri' 8 6 2]
 ['mera' 5 2 7]
 ['rohan' 0 0 0]
 ['sana' 0 0 0]]

In [23]:
print(type(routine_values))

<class 'numpy.ndarray'>

# 10) head and tail

In [24]:
first_two = food.head(2)
first_two

,order_id,order_date,day,order_hour,meal_time,city,area,customer,restaurant,cuisines,...,quantity,order_value,coupon_code,discount,payment_mode,delivery_mins,customer_rating,review,restaurant_rating,restaurant_votes
0,FD50000,30-06-2024,Sunday,22,Dinner,Mumbai,Thane,Rahul S.,The Healthy Bowl,Healthy Food|Salads,...,3,730,BIRYANI30,150,UPI,35,4.0,Worth every rupee.,3.8,2100
1,FD49999,30-06-2024,Sunday,22,Dinner,Mumbai,Andheri,Riya K.,Biryani Junction,Biryani|Hyderabadi|Mughlai,...,5,1140,NaN,0,Card,36,5.0,NaN,4.4,18400

In [25]:
last_two = rides.tail(2)
last_two

,ride_id,date,hour,city,pickup_area,drop_area,ride_type,rider,driver,distance_km,duration_mins,weather,surge,fare,payment_mode,status,cancelled_by,driver_rating,tip
998,RD24002,01-01-2024,15,Pune,Viman Nagar,Pune Airport,Auto,Varun S.,Rajesh Kumar,20.9,76,Cloudy,N,281.0,UPI,Completed,NaN,NaN,30
999,RD24001,01-01-2024,14,Pune,Kothrud,Hadapsar,Auto,Vihaan K.,Ramesh Pawar,3.8,24,Sunny,N,76.0,UPI,Completed,NaN,5.0,0

# 11) Sample :

In [26]:
random_rides = rides.sample(5)
random_rides

,ride_id,date,hour,city,pickup_area,drop_area,ride_type,rider,driver,distance_km,duration_mins,weather,surge,fare,payment_mode,status,cancelled_by,driver_rating,tip
5,RD24995,30-06-2024,6,Mumbai,Powai,Andheri,Mini,Pranav A.,Prakash Singh,5.7,21,Sunny,N,NaN,UPI,Cancelled,Rider,NaN,0
973,RD24027,07-01-2024,16,Mumbai,Bandra,Andheri,Mini,Kavya K.,Prakash Singh,5.7,24,Cloudy,N,136.0,UPI,Completed,NaN,NaN,20
244,RD24756,16-05-2024,17,Mumbai,Bandra,Andheri,Bike,Diya A.,Dinesh Gowda,13.3,45,Sunny,Y,186.0,UPI,Completed,NaN,4.0,0
435,RD24565,12-04-2024,18,Hyderabad,Charminar,Banjara Hills,Mini,Varun S.,Venkat Raju,9.7,44,Sunny,Y,364.0,Wallet,Completed,NaN,4.0,30
631,RD24369,09-03-2024,18,Pune,Pune Station,Viman Nagar,Bike,Nidhi S.,Mahesh Shinde,6.9,30,Cloudy,N,68.0,UPI,Completed,NaN,4.0,0

In [27]:
random_rides = rides.sample(5,random_state=7)
random_rides

,ride_id,date,hour,city,pickup_area,drop_area,ride_type,rider,driver,distance_km,duration_mins,weather,surge,fare,payment_mode,status,cancelled_by,driver_rating,tip
778,RD24222,09-02-2024,18,Hyderabad,Gachibowli,Ameerpet,Mini,Tanvi S.,Venkat Raju,4.9,30,Sunny,N,124.0,Wallet,Completed,NaN,NaN,50
334,RD24666,29-04-2024,13,Mumbai,Andheri,Mumbai Airport,Sedan,Harsh S.,Anil Sharma,17.1,66,Sunny,N,378.0,UPI,Completed,NaN,4.0,0
271,RD24729,12-05-2024,7,Pune,Hadapsar,Hinjewadi,SUV,Ananya K.,Suresh Yadav,3.2,13,Sunny,N,177.0,UPI,Completed,NaN,5.0,0
802,RD24198,04-02-2024,18,Mumbai,Powai,Dadar,Mini,Rahul A.,Vijay Naik,3.4,22,Cloudy,N,101.0,Cash,Completed,NaN,5.0,50
216,RD24784,23-05-2024,1,Pune,Baner,Pune Station,Sedan,Meera K.,Ramesh Pawar,18.9,61,Cloudy,N,410.0,UPI,Completed,NaN,5.0,0